### ISSUE TITLE
Upload Mod to https://beatmods.com/

### ISSUE THREAD

**Issue by ReikoAldrakar** [Hyphen-ated/BeatSaberNoHealthAndSafety#2]
Hey, 

first: Thank you for this great mod xD

Now to my request: Could you please add your mod to https://beatmods.com/, so we can download it with ModAssistant?

Would be greatly appreciated^^

*Maybe I'm just to dumb to find it ^^

Thanks.

**Comment by Hyphen-ated** [comment]
I submitted the mod there in the past and they rejected it for reasons that didn't make sense to me.

**Comment by ReikoAldrakar** [comment]
Hm...oh ok then^^
But still thanks a lot for this mod^^

I only have to put it in the Plugins Folder in the BeatSaber Install directory, am I right?

**Comment by Hyphen-ated** [comment]
Yes
