### ISSUE TITLE
Update for 1.13

### ISSUE THREAD

**Issue by Mystogan98** [Hyphen-ated/BeatSaberNoHealthAndSafety#3]
Hey,

I wanted to let you know that I've updated the mod to work on the 1.13 version of Beat Saber, and would like to release it. But as you are the original author, I wanted your authorization before doing so. You can contact me on Discord (Mystogan#5963), or answer here I guess.

Have a great day !

**Comment by Hyphen-ated** [comment]
Sure, that's fine with me. Thanks
